keys:
  - &admin_kea age1hnaq3zu7tle3jfaqx5r9uw2qgzxl42cc5xek9mwn8dgpaz502s6q5n2geg
  - &kahu age18kkaxamk90rqdxymgaujfy38fetuazmh4uj7fd6p3lh95zm5qvtsyjnyqa
creation_rules:
  - path_regex: hosts/kea/secrets/[^/]+$
    key_groups:
    - age:
      - *admin_kea
  - path_regex: hosts/tui/secrets/[^/]+$
    key_groups:
    - age:
      - *admin_kea
  - path_regex: hosts/kahu/secrets/[^/]+$
    key_groups:
    - age:
      - *admin_kea
      - *kahu
