version: '3'

tasks:
  nix:build:
    cmds:
      - sudo nixos-rebuild switch --flake ".#kea"

  nix:remote:*:
    vars:
      HOST: '{{ index .MATCH 0}}'
    cmds:
      - NIX_SSHOPTS="-i ~/.ssh/id_rsa" nixos-rebuild switch --flake ".#{{.HOST}}" --target-host="root@{{.HOST}}"
