#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    remote_selections=$(awk '/Host [^*]+$/ {print $2}' ~/.ssh/config | while read host; do ssh $host -o ConnectTimeout=1 -o RemoteCommand=none "find ~/projects ~/builds ~/programming ~/ -mindepth 1 -maxdepth 1 -type d" </dev/null 2>/dev/null | awk -v ssh_host=$host 'BEGIN {OFS=":"} {print ssh_host, $0}'; done)
    local_selection=$(find ~/projects ~/builds ~/programming ~/ -mindepth 1 -maxdepth 1 -type d | awk '{print "local:"$0}')
    selected=$(printf "${remote_selections}\n${local_selection}" | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

source=$(echo "$selected" | cut -d':' -f1)
selected=$(echo "$selected" | cut -d':' -f2)
selected_name=$(basename "$selected" | tr . _)

echo "${source}"
echo "${selected}"
echo "${selected_name}"

PANE_ID=""
if [[ "${source}" == "local" ]]; then
  PANE_ID=$(wezterm cli spawn --new-window --workspace "${selected_name}" --cwd "${selected}")
else
  PANE_ID=$(wezterm cli spawn --new-window --workspace "${selected_name}" --domain-name "SSHMUX:${source}" --cwd "${selected}")
fi

echo "${PANE_ID}"

if [[ -z $PANE_ID ]]; then
  echo "Didn't get a pane reference to switch to"
  exit 1
else
  wezterm cli activate-pane --pane-id "${PANE_ID}"
fi
